Mobile version
mmsesay/microverse-capstone-project-one pull request #1
Opened 2021-09-07 10:33 UTC by mmsesay

In this PR I did the following:

- Configure linters
- Create the homepage and about page
-  Add images to the pages
- Add dynamic data from javascript to the main program section

2021-09-07 10:56 UTC, carlos-ssh requested changes
Hi @mmsesay , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-07 10:56 UTC, carlos-ssh commented on .github/workflows/linters.yml
> +    name: ESLint
Fix your linter issues on your Pull Request.

2021-09-07 10:56 UTC, carlos-ssh commented on README.md
> +## Link to project online
**Provide feedback about the video presentation in the code review summary.**
1. A video presenting the features of the project.
2. The maximum length of the video is 5 minutes.
3. A clear and objective description about the project in professional English. The topic and purpose of the project are made clear.
4. A demo of the project, showing the pages in different screen sizes.
5. A highlight about a piece of the code the student finds interesting or is proud of making.

>

2021-09-07 10:56 UTC, carlos-ssh commented on README.md
> +- [OnlineVersion](https://mmsesay.github.io/microverse-capstone-project-one/)
**Your Live Demo isn't working well.**
- All pages, links, and images work as expected.
_Kindly fix it._
![Screen Shot 2021-09-07 at 5 43 47](https://user-images.githubusercontent.com/22258274/132331978-2094ce32-7364-4efc-90c4-02a90e63af8a.png)

2021-09-07 10:56 UTC, carlos-ssh commented on about.html
> +    <link rel="stylesheet" href="./public/css/style.css" />
- Kindly give style in the about page. 
![Screen Shot 2021-09-07 at 5 49 04](https://user-images.githubusercontent.com/22258274/132332645-54948dbc-a689-4c1f-8772-02430082ad4c.png)

2021-09-07 10:56 UTC, carlos-ssh commented on public/js/index.js
> +// index.js
[OPTIONAL]
Keep your project clean and professional.
- Remove commented code.

2021-09-07 10:56 UTC, carlos-ssh commented on index.html
> +<!DOCTYPE html>
Provide a Desktop Size:

1. That divides in a top dark bar and a bottom white bar.
2. The top short bar section with social media links, logout, and language links aligned to the right.
3. The taller bottom bar with a logo and a list of page links.
4. The top bar contains a logo to the left.
5. The top bar contains a list of page links aligned to the right.

2021-09-07 10:58 UTC, mmsesay commented on .github/workflows/linters.yml
> +    name: ESLint
I have resolved this issue. You can check it again.

2021-09-07 10:58 UTC, mmsesay commented on about.html
> +    <link rel="stylesheet" href="./public/css/style.css" />
I have resolved this issue. You can check it again.

2021-09-08 14:15 UTC, mmsesay commented on README.md
> +- [OnlineVersion](https://mmsesay.github.io/microverse-capstone-project-one/)
I have made the required changes as suggested

2021-09-08 14:15 UTC, mmsesay commented on index.html
> +<!DOCTYPE html>
I have made the required changes as suggested

2021-09-08 16:14 UTC, henatan99 requested changes
Hi @mmsesay , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-08 16:14 UTC, henatan99 commented on .github/workflows/linters.yml
> +    name: ESLint
> Fix your linter issues on your Pull Request.

> I have resolved this issue. You can check it again.

This issue is resolved. Nice work! :clap:

2021-09-08 16:14 UTC, henatan99 commented on README.md
> +## Link to project online
This issue is nicely addressed. Good job! :clap: :+1:

2021-09-08 16:14 UTC, henatan99 commented on README.md
> +- [OnlineVersion](https://mmsesay.github.io/microverse-capstone-project-one/)
> **Your Live Demo isn't working well.**
> 
> * All pages, links, and images work as expected.
>   _Kindly fix it._
>   ![Screen Shot 2021-09-07 at 5 43 47](https://user-images.githubusercontent.com/22258274/132331978-2094ce32-7364-4efc-90c4-02a90e63af8a.png)


- [ ] This issue is not resolved yet. There are still overlapping components (in the navbar) for bigger screens (768 and beyond). Kindly fix them. :pray: 
![image](https://user-images.githubusercontent.com/64894927/132544192-581c6e56-3fef-4cf8-97b7-83c9b60608ce.png)
- [ ] There are also components that go outside of the view window (the logo) for the smaller screen(up to 768). Please, make changes to this one.
![image](https://user-images.githubusercontent.com/64894927/132544710-7ad2ffd6-d7b1-46af-90cd-92b52448f4e6.png)

2021-09-08 16:14 UTC, henatan99 commented on index.html
> +<!DOCTYPE html>
> Provide a Desktop Size:
> 
> 1. That divides in a top dark bar and a bottom white bar.
> 2. The top short bar section with social media links, logout, and language links aligned to the right.
> 3. The taller bottom bar with a logo and a list of page links.
> 4. The top bar contains a logo to the left.
> 5. The top bar contains a list of page links aligned to the right.



> I have made the required changes as suggested

This issue is addressed. Thank you for making the requested changes! :clap:

2021-09-09 00:07 UTC, rloterh commented on README.md
> +- [OnlineVersion](https://mmsesay.github.io/microverse-capstone-project-one/)
This issue is well resolved! ✔️

2021-09-09 00:09 UTC, rloterh commented on index.html
> +<!DOCTYPE html>
This issue is well resolved! ✔️

2021-09-09 00:23 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Muhammad, 

Your project is complete! Great job for making the necessary changes recommended by the previous reviewer. I must commend you, **your design is fantastic!** 🌟🌟🌟 ... it's time to merge it 🍾:shipit:.
Congratulations! 🎉🥂

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Kindly consider my comment(s) marked **[OPTIONAL]** under this review:_

<br>
Cheers and Happy coding!👏 💻 🍷 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-09 00:23 UTC, rloterh commented on README.md
> +👤 **Author1**
- [ ] OPTIONAL
Kindly replace the text **Author1** with your full name, so as to make your ReadMe more professional.

2021-09-09 00:23 UTC, rloterh commented on about.html
> +      function gtag(){dataLayer.push(arguments);}
- [ ] OPTIONAL
It is a nice idea to prefer `arrow functions ` over normal functions, so as to keep your _function_ syntax simpler and cleaner.

2021-09-09 00:23 UTC, rloterh commented on index.html
> +      <!-- Headline section -->
- [ ] OPTIONAL
There are comments found in your code on the repository. Kindly endeavor to remove **all** comments from your code before pushing it to the repository so as to keep your code cleaner.

2021-09-09 07:04 UTC, mmsesay commented on index.html
> +      <!-- Headline section -->
okay, thanks for the suggestion. I will try to remove them.

2021-09-09 07:05 UTC, mmsesay commented on about.html
> +      function gtag(){dataLayer.push(arguments);}
Thanks for this suggestion. I will try to use arrow function instead of normal functions

2021-09-09 07:05 UTC, mmsesay commented on README.md
> +👤 **Author1**
Okay.

2021-09-09 07:06 UTC, merged